# **Business Understanding**

*context:*
Customer churn is a significant business concern for telecommunications companies because losing existing customers can reduce recurring revenue and increase the cost associated with acquiring replacement customers. Therefore, understanding which customers are likely to churn can enable a telecommunications company to take proactive retention actions.

*Problem Statement:*
How can a telecommunications company use customer data and AI to identify customers who are at greater risk of churning, understand the factors associated with churn, and support proactive customer-retention decisions?


*About Data:*
This sample data module tracks a fictional telco company's customer churn based on various factors. T he churn column indicates whether the customer departed within the last month. Other columns include gender, dependents, monthly charges, and many with information about the types of services each customer has.

*Objectives:*
- To analyse historical patterns of customer churn
- To develop an AI/ML model capable of predicting the likelihood of customer churn
- To segment customers according to their level of churn risk
- To identify customer characteristics and behaviours associated with churn

*Relevant Source(s):*
- [telco-customer-churn-on-icp4d](https://github.com/IBM/telco-customer-churn-on-icp4d)
- [About Telco customer churn](https://www.ibm.com/docs/en/cognos-analytics/12.1.x?topic=samples-telco-customer-churn)
- [Desk-based Research ](https://elicit.com/artifact/ccce3de9-18a8-418b-8563-4b619089bc96?share_ref=3a69ab2a-a154-40ec-a4eb-80c5bc9aa4b6)

#### **Load Libraries**

In [14]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (classification_report, confusion_matrix, ConfusionMatrixDisplay,
                             roc_auc_score, roc_curve, precision_score, recall_score)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
# from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline

In [15]:
# constants: 
SEED_VALUE = 42
tf.keras.utils.set_random_seed(SEED_VALUE)   # makes results repeatable

#### **Load data**

In [26]:
df = pd.read_csv("https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/refs/heads/master/data/Telco-Customer-Churn.csv")

In [27]:
df.head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [28]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [29]:
df.shape

(7043, 21)

##### **Univariate Analysis**

In [30]:
df_2 = df.drop(columns=["customerID"])

In [31]:
df_2.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [32]:
df.customerID.nunique()

7043

In [33]:
df_2.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [37]:
df_2.SeniorCitizen.value_counts()

SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

In [ ]:
df_2[df_2["tenure"] == 0] # possible new customers

      gender  SeniorCitizen Partner  ... MonthlyCharges  TotalCharges Churn
488   Female              0     Yes  ...          52.55                  No
753     Male              0      No  ...          20.25                  No
936   Female              0     Yes  ...          80.85                  No
1082    Male              0     Yes  ...          25.75                  No
1340  Female              0     Yes  ...          56.05                  No
3331    Male              0     Yes  ...          19.85                  No
3826    Male              0     Yes  ...          25.35                  No
4380  Female              0     Yes  ...          20.00                  No
5218    Male              0     Yes  ...          19.70                  No
6670  Female              0     Yes  ...          73.35                  No
6754    Male              0      No  ...          61.90                  No

[11 rows x 20 columns]

In [45]:
tenures = df_2["tenure"].unique()
tenures.sort()
tenures

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72])

- Customer size is 7043 

**SeniorCitizen:**
-  Binary in nature, 0 representsot seniorcitizen while 1 represents senior citizen
-  5901 are not Senior citizrns but 1142 are Senior Citizens

**tenure:**
- One average the customers ppurchased producin a duration ff 32.37 months
- the variation between each customer duration was appprooximately 24 months
- 75% of the customers fell below 55% in terms of their purchase durations
- 50% of the customer population fell below 29 months
- 25% of the customer population fell below 9 months
- the time period rangers from 0 - 72 with a center point of 20

In [24]:
df_2.describe(include="object")

/tmp/ipykernel_31500/186925522.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_2.describe(include="object")

       gender Partner Dependents  ...     PaymentMethod TotalCharges Churn
count    7043    7043       7043  ...              7043         7043  7043
unique      2       2          2  ...                 4         6531     2
top      Male      No         No  ...  Electronic check         20.2    No
freq     3555    3641       4933  ...              2365           11  5174

[4 rows x 17 columns]

In [8]:
print(df["Churn"].value_counts())
print()
print(df["Churn"].value_counts(normalize=True).round(3))

Churn
No     5174
Yes    1869
Name: count, dtype: int64

Churn
No     0.735
Yes    0.265
Name: proportion, dtype: float64

##### **Bi-variate Analysis**

##### **Multivariate analysis**

In [9]:
df.groupby("Churn")[["tenure", "MonthlyCharges"]].mean().round(1)

       tenure  MonthlyCharges
Churn
No       37.6            61.3
Yes      18.0            74.4

# **Data Understanding**

# **Data Preparation**

# **Modeling**

# **Evaluation**

# **Deplyment**